# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
encoding: 'utf-8'
lang: 'en-US'
title: 'KAIST Concurrency and Parallelism Laboratory'
logo: "/assets/logo.svg"
# description: 'This is my new website'
url: 'https://cp.kaist.ac.kr'
baseurl: ''
permalink: pretty
# avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  People: /people/
  Publications: /publications/

# Footer nav
navigation_footer:
  Back to top: "#top"

google_analytics: 'UA-135907456-1'

# collections:
#   posts:
#     title: Posts
#     output: true
#     description: "My thoughts and ideas"
#     feature_text: |
#       Welcome to my blog
#     feature_image: "https://picsum.photos/2560/600?image=866"
